name: Continuos Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
    types: [opened, synchronize, reopened]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Using Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.

      - name: run intall and build
        run: | 
          npm install
          npm run test

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Using Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.

      - name: install dependencies
        run: | 
          npm install

      - name: Run tests with coverage
        run: npm test

      - name: SonarQube Scan
        # uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonar-scanner
          sonar-scanner \
            -Dsonar.projectKey=meu-projeto-node \
            -Dsonar.sources=src \
            -Dsonar.tests=tests \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.host.url=https://seu-servidor-sonarqube.com \
            -Dsonar.login=$SONAR_TOKEN

        